#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# Test whether we correctly handle canceling a lot

import os
import sys
sys.path.insert(0, sys.path[0]+'/..')
import base
import ldtp
import time

def wait_for_volume(destdir):
  count = 0
  while len(os.listdir(destdir)) < 2 and count < 200:
    time.sleep(1)
    count += 1
  assert count < 200

def test():
  base.setup()
  destdir = base.get_temp_name('local')
  base.backup_simple(backend='file', finish=False, encrypt=False, includes=['/usr/bin'])
  wait_for_volume(destdir)
  ldtp.click('frmBackUp', 'btnCancel')
  base.backup_simple(finish=False, encrypt=False)
  time.sleep(5)
  ldtp.click('frmBackUp', 'btnCancel')
  base.backup_simple(finish=False, encrypt=False)
  time.sleep(4)
  ldtp.click('frmBackUp', 'btnCancel')
  base.backup_simple(finish=False, encrypt=False)
  wait_for_volume(destdir)
  ldtp.click('frmBackUp', 'btnCancel')
  base.backup_simple(finish=False, encrypt=False)
  time.sleep(7)
  ldtp.click('frmBackUp', 'btnCancel')

base.run(test)
