include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

variables:
  BUNDLE: "deja-dup-dev.flatpak"

flatpak:
    extends: .flatpak
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.28
    variables:
        MANIFEST_PATH: "flatpak/org.gnome.DejaDupDevel.yaml"
        MESON_ARGS: "-Dprofile=Devel"
        FLATPAK_MODULE: "deja-dup"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome.flatpakrepo"
        APP_ID: "org.gnome.DejaDupDevel"

review:
    extends: .review
    stage: deploy
    dependencies:
        - flatpak

stop_review:
    extends: .stop_review
    stage: deploy

