image: ubuntu:bionic

before_script:
  - >-
    apt update -qq && apt install -y -qq
    appstream-util
    dbus
    desktop-file-utils
    gettext
    itstool
    libglib2.0-bin
    libglib2.0-dev
    libgoa-1.0-dev
    libgoa-backend-1.0-dev
    libgpg-error-dev
    libgtk-3-dev
    libnautilus-extension-dev
    libpackagekit-glib2-dev
    libpeas-dev
    libsecret-1-dev
    meson
    pkg-config
    python3
    valac

check:
  script:
    - make check
