#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# © 2008,2009 Michael Terry <mike@mterry.name>
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

import ldtp
import sys
import os
sys.path.insert(0, '.')
import base

def check_dir(path):
  assert base.file_equals(path+'one', 'one\n')
  assert base.file_equals(path+'two', 'two\n')
  assert base.file_equals(path+'three', 'three\n')
  assert base.file_equals(path+'top/one', 'one\n')
  assert os.path.isdir(path+'top/next')

def test():
  restoredir = base.get_temp_name('restore')
  datapath = os.getcwd()+'/data/simple/'
  base.setup('file', sources=[datapath], encrypt=False)
  base.backup_simple()
  base.start_deja_dup()
  base.restore_simple(restoredir)
  check_dir(restoredir+datapath)
  return True

base.run(test)
