#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
sys.path.insert(0, sys.path[0]+'/..')
import base
import ldtp

def test():
  restoredir = base.get_temp_name('restore')
  base.setup()
  base.backup_simple(backend='file', includes=['data/simple'])
  base.restore_simple(restoredir)
  # Test restoring everything on top of previous restored files
  base.restore_simple(restoredir)
  # Test restoring just one dir on top of previous restored files
  base.restore_specific(['data/simple/top'], restoredir)
  return True

base.run(test)
