#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# Setup a local backend, but just show the UI.  The user will interact with
# it and test manually.  Good for playing with the UI as you make changes,
# without futzing up your own gconf settings.

import base
import ldtp

base.setup('file')

# Let user play with it for a while, maximum 2 hours
if ldtp.waittillguinotexist('frmDéjàDup', guiTimeOut=60*60*2) == 0:
  base.quit()

base.cleanup(True)

