#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# Setup a local backend, but just show the UI.  The user will interact with
# it and test manually.  Good for playing with the UI as you make changes,
# without futzing up your own gconf settings.

import base
import ldtp
import sys
import os
import tempfile

def test():
  version = None
  mtype = None
  tmpid = None
  sources = None
  dest = None
  for arg in sys.argv[1:]:
    if arg == 'vfat':
      mtype = arg
    elif arg == 'ext3':
      mtype = arg
    elif arg.startswith('id='):
      tmpid = arg.split('=', 1)[-1]
    elif arg.startswith('dup='):
      version = arg.split('=', 1)[-1]
    elif arg.startswith('source='):
      sources = arg.split('=', 1)[-1]
  
  if version is not None:
    os.environ['DEJA_DUP_TEST_VERSION'] = version
  if tmpid is not None:
    tmpdir = tempfile.gettempdir() + '/' + tmpid
    os.environ['DEJA_DUP_TEST_TMP'] = tmpdir
  if mtype is not None:
    dest = base.create_mount(mtype=mtype)
  if sources is not None:
    sources = map(lambda s: os.path.abspath(s), [sources])
  
  base.setup()
  base.create_local_config(dest, sources)
  
  # Let user play with it for a while, maximum 2 hours
  if ldtp.waittillguinotexist('frmDéjàDup', guiTimeOut=60*60*2) == 0:
    base.quit()

base.run(test)
