#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

FILE="$1"
if [ "$#" -ne 1 ] || ! [ -r "$FILE" ]; then
  echo "Usage: $0 FILE" >&2
  exit 1
fi

while read line; do
  echo gsettings set $line
  schema=$(echo "$line" | cut -d' ' -f1)
  key=$(echo "$line" | cut -d' ' -f2)
  value=$(echo "$line" | cut -d' ' -f3-)
  echo gsettings set $line
  gsettings set "$schema" "$key" "$value"
done < "$FILE"
