#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# This file acts like a duplicity wrapper.
# It transforms any instances of "Extracting backup chains from list of files:"
# to "Translation" (to help catch things like bug
# https://bugs.launchpad.net/deja-dup/+bug/877631)

import os
import sys
import subprocess

# Drop the PATH override that pointed to this script
os.environ['PATH'] = os.environ['PATH'].split(':', 1)[-1]

logfd = None

for i in xrange(len(sys.argv)):
  split = sys.argv[i].split('=', 1)
  if len(split) > 1 and split[0] == "--log-fd":
    logfd = int(split[1])
    break

origcmd = "duplicity %s" % (" ".join(["'%s'" % x for x in sys.argv[1:]]))

if logfd is not None:
  dupcmd = "(%s >/dev/null 2>&1) %d>&1" % (origcmd, logfd)
  sedcmd = "sed 's/Extracting backup chains from list of files:/Translation/g'"
  cmd = "%s | %s" % (dupcmd, sedcmd)
  print cmd, logfd
  p1 = subprocess.Popen(cmd, shell=True, executable="/bin/bash", stdout=logfd)
else:
  p1 = subprocess.Popen(origcmd, executable="/bin/bash", shell=True)

p1.wait()
