.TH deja-dup-monitor 1  "2008-01-03" deja-dup "USER COMMANDS"
.SH NAME
deja-dup-monitor \- backup your data
.SH SYNOPSIS
.B deja-dup-monitor
.RI [OPTIONS]
.SH DESCRIPTION
deja-dup-monitor is a session daemon that handles scheduled backups.
It is started by default whenever a user logs in.
When a scheduled backup is due, it starts
.BR deja-dup-applet (1).
.SH OPTIONS
.TP
\-?, \-\-help
Display usage information
.TP
\-\-version
Prints program name and version
.SH SEE ALSO
.BR deja-dup (1),
.BR deja-dup-applet (1)
