.TH deja-dup 1  "2008-01-03" deja-dup "USER COMMANDS"
.SH NAME
deja-dup \- backup your data
.SH SYNOPSIS
.B deja-dup
.RI [OPTIONS]
.SH DESCRIPTION
deja-dup is a graphical frontend to
.BR duplicity (1).
It can backup and restore using Amazon S3, an SSH server, or a local folder,
as well as schedule backups at regular intervals.
.SH OPTIONS
.TP
\-?, \-\-help
Display usage information
.TP
\-\-version
Prints program name and version
.SH ENVIRONMENT
.TP
DEJA_DUP_DEBUG
Set to 1 to enable more verbose output. Helpful for debugging.
.SH SEE ALSO
.BR duplicity (1)
