.TH deja-dup-applet 1  "%DATE%" deja-dup "USER COMMANDS"
.SH NAME
deja-dup-applet \- backup your data
.SH SYNOPSIS
.B deja-dup-applet
.RI [OPTIONS]
.SH DESCRIPTION
deja-dup-applet is a notification applet that carries out a scheuduled backup.
It is usually started automatically by
.BR deja-dup-monitor (1).
.SH OPTIONS
.TP
\-?, \-\-help
Display usage information
.TP
\-\-version
Prints program name and version
.SH ENVIRONMENT
.TP
DEJA_DUP_DEBUG
Set to 1 to enable more verbose output. Helpful for debugging.
.SH SEE ALSO
.BR deja-dup (1),
.BR deja-dup-monitor (1)
