#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# This file acts like a duplicity wrapper.
# It returns 1 as long as cache files exist.

import os
import sys
import subprocess

os.environ['PATH'] = os.environ['PATH'].split(':', 1)[-1] # Drop the PATH override that pointed to this script

# Check if this is a 'real' incremental call (not --version or collection-status)
if '--version' not in sys.argv and 'collection-status' not in sys.argv and '--dry-run' not in sys.argv:
  # Only return 1 if the cache directory has contents.  Thus, if deja-dup
  # doesn't delete it for us, we'll keep returning 1
  if os.listdir(os.environ['XDG_CACHE_HOME'] + '/deja-dup'):
    sys.exit(1)

subprocess.call(['duplicity'] + sys.argv[1:])
