#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# © 2009 Michael Terry <mike@mterry.name>
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# Test whether we correctly clean up from a cancel during backup

import os
import sys
sys.path.insert(0, sys.path[0]+'/..')
import base
import ldtp

def wait_for_volume(destdir):
  count = 0
  while os.listdir(destdir) == [] and count < 200:
    ldtp.wait(1)
    count += 1

def test():
  base.setup('file', encrypt=False, sources=['/usr/bin'])
  base.backup_simple(finish=False)
  destdir = base.get_temp_name('local')
  wait_for_volume(destdir)
  ldtp.click('dlgBackup', 'btnCancel')
  ldtp.waittillguiexist('frmDéjàDup')
  return os.listdir(destdir) == []

base.run(test)
