#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# © 2009,2011 Michael Terry <mike@mterry.name>
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# Test whether we correctly handle canceling a lot

import os
import sys
sys.path.insert(0, sys.path[0]+'/..')
import base
import ldtp

def wait_for_volume(destdir):
  count = 0
  while os.listdir(destdir) == [] and count < 200:
    ldtp.wait(1)
    count += 1

def is_visible(frm):
  if not ldtp.guiexist(frm, 'btnBackUp…'):
    return False
  states = ldtp.getallstates(frm, 'btnBackUp…')
  return ldtp.state.VISIBLE in states

def wait_until_visible(frm='frmDéjàDup', count=50):
  while count > 0 and not is_visible(frm):
    ldtp.wait(1)
    count -= 1
  print is_visible(frm)
  base.remap(frm)

def test():
  base.setup()
  destdir = base.get_temp_name('local')
  base.backup_simple(backend='file', finish=False, encrypt=False, includes=['/usr/bin'])
  wait_for_volume(destdir)
  ldtp.click('dlgBackUp', 'btnCancel')
  wait_until_visible()
  base.backup_simple(finish=False, includes=['/usr/bin'])
  ldtp.wait(5)
  ldtp.click('dlgBackUp', 'btnCancel')
  wait_until_visible()
  base.backup_simple(finish=False, includes=['/usr/bin'])
  ldtp.wait(4)
  ldtp.click('dlgBackUp', 'btnCancel')
  wait_until_visible()
  base.backup_simple(finish=False, includes=['/usr/bin'])
  wait_for_volume(destdir)
  ldtp.click('dlgBackUp', 'btnCancel')
  wait_until_visible()
  base.backup_simple(finish=False, includes=['/usr/bin'])
  ldtp.wait(7)
  ldtp.click('dlgBackUp', 'btnCancel')
  wait_until_visible()
  base.quit()

base.run(test)
