#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-

# Do a simple local backup
# NOTE: This file is not finished.  I'll come back to it later.

import ldtp
import base

def test():
  base.setup('file', encrypt=False)
  ldtp.click('frmDéjàDup', 'btnBackup')
  ldtp.waittillguiexist('frmBackup')
  ldtp.click('frmBackup', 'btnApply')
  ldtp.waittillguiexist('frmBackup', 'lblYourfilesweresuccessfullybackedup')
  return base.quit()

base.run(test)

