#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Emulate pkexec's clearing of environment, but keep test ones
VARS="DEJA_DUP_TEST_AS_ROOT=1 $(env | grep ^DEJA_DUP_ | tr '\n' ' ')"
VARS="$VARS PATH=$PATH XDG_DATA_DIRS=$XDG_DATA_DIRS XDG_CACHE_HOME=$XDG_CACHE_HOME"

# Test that first argument is our custom duplicity polkit script
echo $1 | grep '.*/deja-dup/duplicity'
shift

env -i $VARS "$(dirname $0)/../../tools/duplicity/duplicity" $*
