#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

import sys
import ldtp
sys.path.insert(0, sys.path[0]+'/..')
import base
import subprocess

# First we test how things work with defaults, never used
def defaults():
  base.setup()
  assert base.get_settings_value('folder', schema="S3") == "''", base.get_settings_value('folder', schema="S3")

# Now test when there has been a run
def has_run():
  base.setup()
  base.set_settings_value('last-run', "'foo'")
  base.start_deja_dup(executable='deja-dup-preferences')
  pout = subprocess.Popen('hostname', stdout=subprocess.PIPE).communicate()[0].strip()
  assert base.get_settings_value('folder', schema="S3") == "'%s'" % pout, base.get_settings_value('folder', schema="S3")

# Now test when backend isn't s3
def is_not_s3():
  base.setup()
  base.set_settings_value('backend', "'rackspace'")
  base.start_deja_dup(executable='deja-dup-preferences')
  ldtp.click('frmBackup', 'btnJustshowmybackupsettings')
  pout = subprocess.Popen('hostname', stdout=subprocess.PIPE).communicate()[0].strip()
  assert base.get_settings_value('folder', schema="S3") == "'%s'" % pout, base.get_settings_value('folder', schema="S3")

# Now test when folder isn't '/'
def custom_folder():
  base.setup()
  base.set_settings_value('folder', "'foo'", schema="S3")
  base.start_deja_dup(executable='deja-dup-preferences')
  ldtp.click('frmBackup', 'btnJustshowmybackupsettings')
  assert base.get_settings_value('folder', schema="S3") == "'foo'", base.get_settings_value('folder', schema="S3")

base.run(defaults)
base.run(has_run)
base.run(is_not_s3)
base.run(custom_folder)
