#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-

import base
import ldtp
import os

def test():
	os.environ['DEJA_DUP_TEST_VERSION'] = '0.5.02'
	base.setup('file')
	ldtp.waittillguiexist('Error')

base.run(test)

