#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# This file acts like a duplicity wrapper.
# The environment variable DEJA_DUP_TEST_SKIP_FILE points to a file containing
# numbers of volumes to skip. 

import os
import sys
import subprocess

# Drop the PATH override that pointed to this script
os.environ['PATH'] = os.environ['PATH'].split(':', 1)[-1]

extra_args = []

if 'DEJA_DUP_TEST_SKIP_FILE' in os.environ and 'full' in sys.argv and '--dry-run' not in sys.argv:
  # Read the skip file to see what we should skip
  f = open(os.environ['DEJA_DUP_TEST_SKIP_FILE'])
  all_volumes = f.read().split()
  f.close()

  if all_volumes:
    f = open(os.environ['DEJA_DUP_TEST_SKIP_FILE'], 'wb')
    f.write(' '.join(all_volumes[1:]))
    f.close()

    extra_args = ['--skip-volume', all_volumes[0]]

subprocess.call(['duplicity'] + sys.argv[1:] + extra_args)
