.TH DEJA-DUP "1" "" "deja-dup" "User Commands"
.SH NAME
deja-dup - a desktop backup tool
.SH SYNOPSIS
.B deja-dup
[OPTIONS…]
.br
.B deja-dup
--backup
.br
.B deja-dup
--restore [FILES…]
.br
.B deja-dup
--restore-missing DIRECTORY
.SH DESCRIPTION
Déjà Dup is a simple backup tool.  It hides the complexity of backing up
the Right Way (encrypted, off\-site, and regular) and uses duplicity as
the backend.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP
\fB\-\-version\fR
Show version
.TP
\fB\-\-restore\fR
Restore given files
.TP
\fB\-\-backup\fR
Immediately start a backup
.TP
\fB\-\-restore\-missing\fR
Restore deleted files
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "SEE ALSO"
.BR duplicity (1)
