.TH DEJA-DUP-PREFERENCES "1" "" "deja-dup-preferences" "User Commands"
.SH NAME
deja-dup-preferences \- desktop backup preferences
.SH SYNOPSIS
.B deja-dup-preferences
[OPTIONS...]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP
\fB\-\-version\fR
Show version
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH "SEE ALSO"
.BR deja-dup (1)
