#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 2; coding: utf-8 -*-
#
# This file is part of Déjà Dup.
# For copyright information, see AUTHORS.
#
# Déjà Dup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Déjà Dup is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Déjà Dup.  If not, see <http://www.gnu.org/licenses/>.

# This file acts like a duplicity wrapper.
# It transforms any instances of "Extracting backup chains from list of files:"
# to "Translation:" (to help catch things like bug
# https://bugs.launchpad.net/deja-dup/+bug/877631)

import os
import sys
import subprocess

# Drop the PATH override that pointed to this script
os.environ['PATH'] = os.environ['PATH'].split(':', 1)[-1]

extra_args = []

p1 = subprocess.Popen(['duplicity'] + sys.argv[1:], stdout=subprocess.PIPE)
p2 = subprocess.Popen(["sed", "-s", "s/Extracting backup chains from list of files:/Translation:/g"], stdin=p1.stdout)
p1.stdout.close()  # Allow p1 to receive a SIGPIPE if p2 exits.
p2.wait()
